server:
  port: 8082

spring:
  application:
    name: trade-execution-service

  datasource:
    url: jdbc:mysql://localhost:3306/Fin_DB
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

logging:
  level:
    org.springframework.kafka: INFO
    com.fa.trade: DEBUG
